---
privateKeyFile: ENC[AES256_GCM,data:swpN4TfpyBmSRbOXrrBAu8M=,iv:gNOox6UifzIzEA16Q7G5rKeb9rPIfHPBSwc8qGRBRHc=,tag:XMkB71hOzvrjDlItolyDBw==,type:str]
workspacePath: ENC[AES256_GCM,data:63J97GjC,iv:JsqJorwNwmxqYRBK/WkzgsZdPwazFjlrqw7xJwQ8qMk=,tag:uB8alEhrDLeq0KWL1fzRng==,type:str]
gitUsername: ENC[AES256_GCM,data:IS+e0PwmgA4=,iv:tuE2qxONe+j8Q0EmSbXIWEbgICKLLqXDLxj22z2CCRM=,tag:rrTACzx0z+zIZKN7ZA1vKQ==,type:str]
noCategory:
  - ENC[AES256_GCM,data:khntkNHLQmz/Mg==,iv:am9WwGIwGuJLYOXotEB7tau5YxgBqIDjMBLcajgZeyc=,tag:D11W1QkX0ieDHRfvJUuQUQ==,type:str]
  - ENC[AES256_GCM,data:I0by87//,iv:bvoI3VDADBufhhC5LfAqBvk1QTC4drs7ho6pOBuSSek=,tag:jUpmg/f10aruipSoXA80QQ==,type:str]
category:
  - group: ENC[AES256_GCM,data:7uovFWj6mQ==,iv:2k2cYXmMvOIcxY2H+S2+yUSnFmMdKji5uUTOemNJHDo=,tag:5yRUApU1tfQ8OM4CwIFQXQ==,type:str]
    repos:
      - ENC[AES256_GCM,data:VAMlpvDx4eK+k6sWI/XeHPfYmYY=,iv:v81V2ngJzrrU5LvQlDccL1lv0Qp43bArc1CUWZlmlz8=,tag:dHObUBwPWn0uV3ITyT/mkw==,type:str]
      - ENC[AES256_GCM,data:Wybcr6Um,iv:Thg9JZNY1iI4m/C2NbZds09D6iGLWAYfqdlLPKNnHYw=,tag:FstPrgVyfQRw4B3tNK+SSw==,type:str]
      - ENC[AES256_GCM,data:i9EppP9zXzKNDxYg5TVol88=,iv:k/M/pdKhQZIUkBkCd3wchjeJlfp7lj8okkz41YNaQnk=,tag:tp0Jn1VLVNxLLbzCGhJI8A==,type:str]
      - ENC[AES256_GCM,data:p7a5bvIhvbXj36mHMN7YMdZmwr2Y,iv:tD6tA13Iz7ErczDMPHrj1/nQ0kenSgs84ht6/1RRRCk=,tag:xnV5iyjf0vwSeunjaPb5+A==,type:str]
      - ENC[AES256_GCM,data:bPcymXueryb5AkmD/yc+,iv:ddTK8Quk94u0LNQKTh8kCoNhgxSNk/x9S1kRanMXY0o=,tag:GEBUxjXpW429SF1R4pD5dw==,type:str]
      - ENC[AES256_GCM,data:NpQkatcspA==,iv:bpGYg6YCaWQmllfHg0bEKwPowiRGZteyIuTmzV0vwRA=,tag:uEw0mK4wy25AlW/F2cUNwg==,type:str]
  - group: ENC[AES256_GCM,data:cKu32K4=,iv:wTfCzNwakrjAZVLj4tQgnM2sfx7UxyDsfQsiR8kXbWo=,tag:tdGJPHSMuwfXVxY20g/49A==,type:str]
    repos:
      - ENC[AES256_GCM,data:t98FQk2e8QSjWw==,iv:9M7F/fRixxDwOtf/ukcfs0zQ5YpVgo5Cef5jnmCBqAw=,tag:c+8/9ObrBSHDNsb82grqfw==,type:str]
      - ENC[AES256_GCM,data:t0wGCW7CvKmnE/a3Fg==,iv:YfCdIal8LQzDbv8tBwQ9YUEFJ4dbnQcCa2QO/sdc9Fg=,tag:bgmQSKHvQGDcN4nmWtCysA==,type:str]
      - ENC[AES256_GCM,data:sLiTyQ==,iv:iUOwAd2okBZw6TTa6Z+P830WUBbO3TbJz7dCjS1pNgw=,tag:F8aVdCOFaG2V1gI2eEcQ7A==,type:str]
      - ENC[AES256_GCM,data:ruhpbyH1MOXQpDU=,iv:ra7MFkk6eoDE3Dv5nDmiMBaDEY81oBtdhgNVbBd2uVk=,tag:J7/gMMq61NWx9GurD3nA+Q==,type:str]
      - ENC[AES256_GCM,data:CFtdpv4gPI299BXIqw==,iv:SlZXXhRkIWe04cfUnPWfriIZ+eMVjMLtBkCLtfzb4bc=,tag:VNh8s/vF6mJCq9c6gMnHMw==,type:str]
      - ENC[AES256_GCM,data:jrJm8JN0yWbfaX4=,iv:oW4jgB/v22WwPCLqGinlttCYWEzryzNRUXgZ+UcwUrA=,tag:i/10ARnGncUgyDk+7myzhw==,type:str]
      - ENC[AES256_GCM,data:S2qIoXmWPPs=,iv:yH7pMt9fMG8nwq9jB+5PZ29rnJcep1wXJ5axW6M2NXY=,tag:5qK20EjYu6S5r188+rbT0g==,type:str]
      - ENC[AES256_GCM,data:Rll8cyUk3otJx7Y=,iv:5Vka0H+2bpEQy830nYuY9MwbPuJB5E1Kovs1UchkKX4=,tag:AJJpYZv7cD+Oi+BZCeFruQ==,type:str]
      - ENC[AES256_GCM,data:AdjQMZd4,iv:kLps12JaOWruZPoof2LQlBZ3KCEjg9jOMV2LQXTbDkU=,tag:jnk0vKo/yvNU1qRHMp8t/g==,type:str]
      - ENC[AES256_GCM,data:PejSSiAXZpHU,iv:ExBCLAJV23V5/9nazwW2ICpo7P3jRPLlSouqMlK6720=,tag:UyLCCe7+2Rstmp3sjINyRQ==,type:str]
      - ENC[AES256_GCM,data:AD8l4Ph8QXg4J+1PMeBM,iv:TiT6EKQxGPre9y9cpNa2qC8gO7DToU743NcoKS9pyc0=,tag:9nuYory0244d/b/IfM7sXg==,type:str]
      - ENC[AES256_GCM,data:84fl1QFLoj4i/Wc=,iv:G60XsDdeEbgyxrTCrRX90JdV83PN7bRwnYzQ59KmCo8=,tag:naViR/U2PRD006LWANLoVw==,type:str]
      - ENC[AES256_GCM,data:5m1MH+Oil8GeFk1P+vhWwDyTWeSZWlmhuxIP,iv:LQWhjC0maXv0uxxMfU8ATUNdW0xw1J86ghYIXtC41uk=,tag:vw8QkWZGECmi1wAAVr6hIg==,type:str]
      - ENC[AES256_GCM,data:ZEOBbUO6c9p0dXkP2A==,iv:37aFp4SvKhadspNwM+pa3+p5IfdJtEm5wb5HbN2FGhk=,tag:rtRtSwYfTQEqXr1fZ5l4kg==,type:str]
      - ENC[AES256_GCM,data:jqWqfSu3Ma8TNU1etRhfNw==,iv:vl4M5qm+K7vytt+JTmvY/OoY12mdMw+FZz+YIcmt8Ak=,tag:KRoodLXsUELZEP3JbXGCfA==,type:str]
      - ENC[AES256_GCM,data:GyAHXBHWU73lPKE=,iv:2HoxbC37U4gMLiDdAq6mX6rnkxzo2sQxXj2kPZ5MJVg=,tag:/V7goIqWf+8qqtCrY5OhOQ==,type:str]
      - ENC[AES256_GCM,data:Fp9kGIKiPyH1qMDT2hrGFA==,iv:b54Nbx/Z2HVhFxehiSQ+le+IbIQtTpNoIvC4CQeKB18=,tag:2AABzErFQYcQWPXR1iFf2Q==,type:str]
      - ENC[AES256_GCM,data:2En+9HrQC7C9KZoRLXaPsw==,iv:jRTQdymKeXFwNjgKv+6xUA6qkxm37rUxf0MxwUCgrxo=,tag:xZn2HWqJKHfJ+GGxO7D43w==,type:str]
      - ENC[AES256_GCM,data:rFbrSN6A05uq1RUTVwU=,iv:UCz16MkS9ATg2VfFi4fwR3nzMypenp2yQcNiimu3PPk=,tag:WIKNUYVDJ3nbv/7Borrd6g==,type:str]
      - ENC[AES256_GCM,data:0PF3fA==,iv:zi24RjMDsHt8sJzweaGW06ov1F5RA6Jnj7+fBaJPXcI=,tag:yzg7oc4hD+OMKy91X6IAKQ==,type:str]
      - ENC[AES256_GCM,data:dbhB84QceQ==,iv:182FSaccVbMYTU4VHMPMsvxqQAQX6dJ42HPXg0PKqfI=,tag:4tiUCfs6jkXXmI9+SKIheQ==,type:str]
      - ENC[AES256_GCM,data:1B6rGSIvcfK+Nb8ok2kaiztMqs9kowZ3d21n,iv:WQ91IyGAh7t7ES9ZkXALN0Qax3tgQMBEKFq92CtpfnU=,tag:lz1v1A8XCEHq++tb9Chp7w==,type:str]
      - ENC[AES256_GCM,data:pvndlret0PrZt3A7u6Vjuu8=,iv:mj3XcHec2VQnOZftr0TfFPT9zjOVEGpXE0fRK4VmHtI=,tag:/HBoPITcPetSmMIpnyc+mw==,type:str]
      - ENC[AES256_GCM,data:TXKV/53wkJwS1IkFxFRaUk0=,iv:jsZzAwaJqj5vbAyVyOFn6qHixCsHMMLxfzdmRmM5tYo=,tag:TjtPYLXPeqaZ+lb4mcKLSg==,type:str]
      - ENC[AES256_GCM,data:C6jDhefVDp6jR/0lZjP6,iv:0H7jvqIW5f6EuYVmD48MINZVQEI56iFh+X7hQWCvQ9E=,tag:xDKoeeqJ0ztTYoJS6JWK5g==,type:str]
      - ENC[AES256_GCM,data:8M9RMbRvaW3DWA58bD6XT5I=,iv:HW2geQs/PKa7audz8wzKPy0dGpKdX6yExRBlIUvGn+A=,tag:BaOPEC5AWIMqddmwYgcKuA==,type:str]
      - ENC[AES256_GCM,data:YkP8VirNbHXHxtJraQ==,iv:5fkVLrHQ5oj6nEqgiwD/XAN4ZrcgbTYiubiNedCHQpI=,tag:WExX+24AewJUFFnCtNqMeA==,type:str]
      - ENC[AES256_GCM,data:cqk6kJBb/qpuX3bTRpMA+Xo9,iv:UB6+1TW4KOt/pbdUBgy6BSbAbej7GElzUYjgy0Ifa8g=,tag:RISkIVX4TrmE062IR7Lt/A==,type:str]
      - ENC[AES256_GCM,data:HkYqL9znsptWUew=,iv:yOahYZUKdQEgUSraf5aEK2SAfA/rjZFEITTsU+3WgAU=,tag:P3hhfsjU/gRkwLTncVT5Pg==,type:str]
      - ENC[AES256_GCM,data:KxtD,iv:v2wO608rA4t8mY/kUHixI/AzRa4VarGE/9sMyVbnSnk=,tag:Hu9MeromiF5zdno1nj7tLw==,type:str]
      - ENC[AES256_GCM,data:OAkZjPY8NoJ2,iv:nrYOZdx8e1e3GtynaO7I12WXDpzPnQYMYdM1vEkhRRs=,tag:bPrNtk02WuLTD7pF2ew8YQ==,type:str]
      - ENC[AES256_GCM,data:YC0cGR9f0CM=,iv:jhyqjNLtRlfIwqIMkm7oi2uxziUG38lTFEKpHyhyaX0=,tag:BseHEBgyFqJINjDPl37iug==,type:str]
      - ENC[AES256_GCM,data:0vlrhgj2yjgd,iv:kwfloVIy97rpfPRMzWJ28skOmFICxK5PzdE8fL7ULqE=,tag:63tFcXdvnRMlSI8bqkVZXQ==,type:str]
      - ENC[AES256_GCM,data:eInobIwFWYLoYw==,iv:p/I1rRlStKcMDGhEtbh4Kx4lnX03TnYanfIGed0ppaI=,tag:8PqMgJqEt82xXCz2QkW/Bg==,type:str]
      - ENC[AES256_GCM,data:BsgD0nDMudXJ,iv:++z/k1Ios8pQ3Tf/QFRSOgJ/GtqWkXtbJPRTGR7Y/Yk=,tag:IEMWwg1oVgf8NrVBgP4xmQ==,type:str]
      - ENC[AES256_GCM,data:PUHg2ZRw9mAhJrj+ww==,iv:nzhsOxfyK5b/B4MwsuElGpMVSPFLws+bYJYZmN2WfwU=,tag:hKHulEqtUP7k1LQk5lXamw==,type:str]
      - ENC[AES256_GCM,data:LtDzGbfk86VZ8Qw=,iv:ZrpW/yTYmgueQfMVT+WyrYIRcsJOBtAoP3bFpiHmMkI=,tag:7Pxm4o9XxlxeLLPYPM9dYg==,type:str]
  - group: ENC[AES256_GCM,data:Yjg=,iv:poH6eanipFR/inwi8bDtH+chR0V/r7M0nykIjd/K1O4=,tag:yiJDJUxgCSqmE94e2z8g1Q==,type:str]
    repos:
      - ENC[AES256_GCM,data:Td7c,iv:CvjBf6FFwSlvnUxGgP5WY84mo2kAqHyIqL3ZkTHsgtA=,tag:dU3ZjGEbemJ6dCBFEyIzRw==,type:str]
      - ENC[AES256_GCM,data:rjg9snP2GskTR0pstVK5EQ==,iv:wMT82KOkZcW/+teAO+G6dmOb3cHZMrjLqw0In7kerf8=,tag:VhVDcz/e4vAXVmoFNwiUeA==,type:str]
      - ENC[AES256_GCM,data:bx9e,iv:1tdm+PmExGtl41K0F73NtbZdlU8mNboZYSo6F1fGWIo=,tag:aaAS6nKZb864gThtzMA15w==,type:str]
      - ENC[AES256_GCM,data:FflFcwKQ,iv:Bb4FWhnK2XeuUhgqYmnvY0nXfMDpmUmKBZCk7YaeZeg=,tag:WWTbGbuTFAOC49Bmlu0fkA==,type:str]
      - ENC[AES256_GCM,data:wARTlXjNSrOzFGTZTeYjkvgK8adK3iWJcujtXsR+vHc=,iv:4TiTvZxgMg+8T4BakktNCrbcAPWTISsrAloxv1Q6AKs=,tag:5w7cDu+yMJZn4m2jcOrLoQ==,type:str]
      - ENC[AES256_GCM,data:KUezn+WD,iv:e0byrgi0dPLzdGlwfqR2h/mfigHgx6G8c1GG4dkF2Ss=,tag:ThMINl77yImmY/lGk0T9HA==,type:str]
      - ENC[AES256_GCM,data:V2S72IZjxVC/fzBY,iv:4lrXU1eNOYNEg4htYTGLeN09Qn4dLJldl7LWUZq9wa0=,tag:B3aCu0wJNnZCst2f0Oc2PQ==,type:str]
      - ENC[AES256_GCM,data:5Z2h60RmEbh98ckRsnZ24u+TzMYDHg==,iv:aX0TUdswlbTVyzlWUODsPhOhPBA1fiGkI6GOJZtjsy4=,tag:EvLtY17hXdHBNPjCjxdLYw==,type:str]
  - group: ENC[AES256_GCM,data:1jkf2Jw=,iv:UT2S9kwpwyNfQ2F+AD3TOQR2TaZS3yMX1HUGmbuqLOA=,tag:QEN1PjoT8LsyAz+puY3k7A==,type:str]
    repos:
      - ENC[AES256_GCM,data:bURY9ssqte4k,iv:1wMo6535/a9kiXM6nI5b9zXdV+ZlRCr5hTV/enuYRHw=,tag:dhq07i3ItYRH3wvOtDRxlw==,type:str]
      - ENC[AES256_GCM,data:zw0/og8=,iv:aS1o05qup0KahSOV7glQ6YL9nLfZqLYrgEpOvmpo66w=,tag:WTx8xRvpyCzZoPJHniNlKA==,type:str]
      - ENC[AES256_GCM,data:Gntykb09xZGIl6cmkLg=,iv:YkO66D7MZ3Z9Fm5yRfnwwBMXSReWk8OHSt8vw6kt8+M=,tag:3BjFRnwAp1O/9+AMvdhZUQ==,type:str]
      - ENC[AES256_GCM,data:jt4Wh5YnrIP5qQ==,iv:Q/M7WNfD5bEmHbvhMMK0D2JGi85+2JJx+GdHm4FPdcU=,tag:GPbzOrRLmBrYhTul/e0B8g==,type:str]
      - ENC[AES256_GCM,data:T8t4+o7ZArEAznPpxQ==,iv:7JmnAOslFU4Ldk5hy3OU0Apsc64SRM1lzVFCc0kKg5g=,tag:iyV+vN33Ll+gSoRD4xlgnw==,type:str]
      - ENC[AES256_GCM,data:J0p3cWN6Sz4b3gim+cK+Zlqs9Z1KOPTD,iv:D8Eed6roMm/G/kpfbfaJHXEGZoyZFbN47K/pDlzNSGo=,tag:gx1Egz+DVVsd86mJceSaTw==,type:str]
  - group: ENC[AES256_GCM,data:Jau+p1Hb68s=,iv:ipvEDR+Ze9HvxLoMgy/b4eQCsr7Va5378lMmilI/2UI=,tag:wJD6QQTB3UGWAQLCptXO2A==,type:str]
    repos:
      - ENC[AES256_GCM,data:of+y,iv:l9JPFM+5mY1eJRmgzXgFfIXYLDEO7c2ROAJj+c05how=,tag:YpFlyFzL9ogW4TcSctEgQQ==,type:str]
      - ENC[AES256_GCM,data:08o9nVA2LyCU+h0=,iv:9JMUcQtoPVGLvTV9rlZBFhOG863tTpLkAcM8HL0AjMc=,tag:cChkUFT+1GrPRiDEMvH29g==,type:str]
      - ENC[AES256_GCM,data:URTgKjVLw+Z/PPUHuCM=,iv:Nb76VzhVbTU9/rGNIZGI1rh6HOo/wi6P0BAxtE7LLNg=,tag:bUWOt/6V81cuuG7zsxEq3g==,type:str]
      - ENC[AES256_GCM,data:TK+9XhPC,iv:ZAsHe7yApkpk8sIxjTBFV9Hb4SGzN4TU67otcQIcaiY=,tag:D+0JeGsr6Q6uVySu+V6NGw==,type:str]
      - ENC[AES256_GCM,data:I1GMXUIkZXONuDRVCWS1bg==,iv:O42d5Q3YsY48ke/Xt5NJ0xhhovCNx3ds6G0/0f2/blQ=,tag:RnJhnRtll7d/CKCV5WYDEQ==,type:str]
      - ENC[AES256_GCM,data:zhcXkeNNhBBp0rsdIg==,iv:kyFiRD1qeWT6z6LHmIqOD+EziBUBRZ3d7qpcVfD7bZg=,tag:94XgQ5EU2twt9fffoSAGOA==,type:str]
      - ENC[AES256_GCM,data:Sh2nqRwH0De8Y3TndKJGbPYrUCkKv67dfQ==,iv:eN/3yByAsE3glVfoDheUgkYToyS5+7d6jykSKLp7fk0=,tag:5gBo3ZLgyYzXGQC/vu6Krw==,type:str]
      - ENC[AES256_GCM,data:r68MhLNx2aLL0TY=,iv:ndGhK4FZnoNk8JcKQFK1eZU++jGRG2fWL1ctMBmkAHU=,tag:7JYQ8jhHAixLTFC9zCy3hA==,type:str]
  - group: ENC[AES256_GCM,data:4WODpZBu2z7mRA==,iv:bMfywMF5OvYxLLvlejH6wsa486Su0WM04jFFK04DPG0=,tag:gkW2/Wk6TYQ7YfHXzf5L9Q==,type:str]
    repos:
      - ENC[AES256_GCM,data:LPBMnmwsb/QYRbcuZFkdxFoVdFvWKyfLJPF1nGfOYWOj,iv:MB4aYi/ZBhyoyXUvoq/c21FhJtXvpdxy9n/OWsD+WJo=,tag:em3IH2cFmvK85bi4ueBAuQ==,type:str]
      - ENC[AES256_GCM,data:3CeINakOh/gTj0ZC6Eag,iv:BU8id/UZKzcJ9vpxaQ5fVqwf6WxNMB8IvA2tBDwUvxs=,tag:cgAnu+6l155TRlEHbA3dNQ==,type:str]
      - ENC[AES256_GCM,data:vFRKNaxaNnuqX3+RzIsz,iv:R6gbDJ+zaIYlU69i5OT/SMD4gqQd90gqmRsjaWGGkhg=,tag:xkwsnufy2zgsUupkOtyVrw==,type:str]
      - ENC[AES256_GCM,data:zaQ5bpPhUSis9H442VUs,iv:HE/M/4E/YMnqfCmoyQE8I5uEH6IAAQ2D0djXCWEJvcY=,tag:PaOtrnu5FTaCaKzq8V2tUg==,type:str]
      - ENC[AES256_GCM,data:J1v2Oiy/0BWcq7M3cUbFNqO9,iv:0GuLl4a4N5kPI3En6QsJPcBEa9251eMrw49jP013qM8=,tag:zOVYDGHm2tEcL1y2yn4E2Q==,type:str]
      - ENC[AES256_GCM,data:ankSdyiWqr1CG1cOHVg2fQ==,iv:V2HL6hZVNf/4nK2rNf/Yaf2UrMOvx5ZnSis3Rcsyg+c=,tag:mAwUrfpfKToflzjWsx7eng==,type:str]
      - ENC[AES256_GCM,data:Ru8HnZJ/HLies0Lqhm2a+TU=,iv:dhUosCjC8g/b21BSlxn1Kf+bQp23DE7IFH2NvH4OyMs=,tag:Gy/5bqUSuVHZaB0a2O3RQA==,type:str]
      - ENC[AES256_GCM,data:G9Xux8My9rDcnxGPNA==,iv:vEZY/MXogSjzS5R5grR5hpPgHX0hUj7VnVCo9EeLr3g=,tag:zL2CoUG5NRCjGIwW11HZeQ==,type:str]
      - ENC[AES256_GCM,data:G6QmfsNOrjRCUVacCw==,iv:bvNBFOU3qd9nTVonyxq3rsUM6tkbDje7pOeWuc0xVkM=,tag:hefCEvJrfJzFGYrmTjDsZw==,type:str]
  - group: ENC[AES256_GCM,data:YMlj7m2aOEY=,iv:+jr3SQiQk9VqQBpUQSCkVanNOT1zgWXz72mX2dK2R78=,tag:wboRmGnwkPlFbBxZmfgRUQ==,type:str]
    repos:
      - ENC[AES256_GCM,data:UetgquhaXTr4TKvpiss=,iv:L2mynbEwnrMp5W8JkgV3G/wyY2rYY4z/5/bpFuMf2m4=,tag:JCJeJX3eRh8Dj6f1TQo5IA==,type:str]
      - ENC[AES256_GCM,data:v+XuOAaDFg==,iv:H5Ks56phtPS/8t5nlhu+gP6z73nMCtvR5hKqDOgq2Yg=,tag:uARSFtJHUHP2YGZ/8GyIFA==,type:str]
      - ENC[AES256_GCM,data:EMIQM9OrgP4WZnjz7A==,iv:uyaC+UaJrmfI9wuhidR3OFWqK1kHigKRlDoCSrmWr84=,tag:/dsxukHIp7DVEiIYs6nGmg==,type:str]
      - ENC[AES256_GCM,data:k7CYIzWnAfXWbzu2itA4rRKrEOHY,iv:cqwj0NnOtbk4lYo/VDUU9sJIHKkrkE6MoWIzZh2Cgx8=,tag:UhmFnx8JgYUuzuZzgfiAUw==,type:str]
      - ENC[AES256_GCM,data:AEjfOFtGyvSrB0/JmDtUTxYPww==,iv:gWk0fy78o3zlSrIs/j8G/n3SCf08S/L+0d9sMQq4FsQ=,tag:wTIEFs2RkZUGrPJEXtf5xw==,type:str]
      - ENC[AES256_GCM,data:mhKxwEiw8xX8Dx0kp2qAew7tw0TnDZGFEVg=,iv:Ha9VhI+60PiCbNHLnJ/OeeslrWPkDHG+mHeUWrfg7/g=,tag:+qAhjbwaJ/a3T+j7dPhKsw==,type:str]
      - ENC[AES256_GCM,data:VwFrM8wc/E+8GfhFxMQrsVodJszc9w==,iv:dysFPOksYAOxgvhNeEOquwd5LqqeDKvlQZVzS2OvEE8=,tag:9CFfVocda4PW3gnL/E26LA==,type:str]
      - ENC[AES256_GCM,data:sxui7Nk/o3/DLZT29KrT+BVlxWdwNYsjec56eEFuqQNv,iv:L0Iq8ZIKQfIQH7MF/Qz9y6MFq16TyGBgiLWoMZfKi4k=,tag:II1a6o/4FxjncbqZVvfL+A==,type:str]
      - ENC[AES256_GCM,data:S7TZnxS4nW4gaU7e,iv:UbMnzLrzehXXyTZmxYgbHoZFXRnFsQ8BccivGr1UOuQ=,tag:/4LYn6Bku64J0TMH7l6yBw==,type:str]
      - ENC[AES256_GCM,data:ZW2mQXfi54SeAu97ViyYw9PlrpMhuAXqhUOw7S3z,iv:U6XrBO6RhDUMmtw9Um56YrDrJLoowfxtTcyEOa6LvrA=,tag:V9Wn5IbWVYwEcPqwvwWicg==,type:str]
      - ENC[AES256_GCM,data:lzRkJoTbFgDRD+tdGHKL7GA6AkJdFahfBRXYwAQ=,iv:qEG2iQVJqvKOG47UnYuA8bx8aPrdQ1P4A4WjkfeztLI=,tag:l1fSHfeYjYgfUZF2hBeUJQ==,type:str]
  - group: ENC[AES256_GCM,data:aG1FOYs=,iv:KUaw1yK7czEJKe83MupcAOmMhFkNCSmrNaANa9dAVmw=,tag:diw5sMM3Olopfsc543TfTA==,type:str]
    repos:
      - ENC[AES256_GCM,data:Mbn6d3aYiLhVE8QNxd6Wvgws,iv:sL0XVr93DgR73mAu7JF4o6YsWYyzkFB6jTOWYQ90YA8=,tag:CpSREWB8RH8qcXycB+brvg==,type:str]
      - ENC[AES256_GCM,data:PV1rBJ2Z1FiWWzU=,iv:lEmJbRx+rj4voQuufK97DU+RJeCTbL64DnRjFdpH8IQ=,tag:gq/bWoB3OsompiXPrvfz/Q==,type:str]
      - ENC[AES256_GCM,data:zD08Pdghb81jvQ5QpQ==,iv:vKP05v6GXVh6A5NgKZ1wIYJDfi3ZonCapNZRgYeleM8=,tag:bKQAnzOdTknmvqfNvlxhjw==,type:str]
      - ENC[AES256_GCM,data:aEGqC6G78lV1kKM=,iv:rmI1dhUb2TvTiC8TVB6fN+PPlhfO+UKNljZ8VHI7dq8=,tag:XdlT48NDmzbbKAvtImQ7Jg==,type:str]
      - ENC[AES256_GCM,data:W2BDTX/Qt3/pCSvVUsZgTVKwKw==,iv:ziEAMw24Yhe11b4A6EuDz8bTofUBcCg/pT/FV6JYcVM=,tag:TS6fSnmVJHBZLuAdbCESoA==,type:str]
      - ENC[AES256_GCM,data:r560t/Nl,iv:ZUYJYdkGtWjKJbvWLm0n9+/APTEGc7BK8IqyyoJc3aQ=,tag:f05LJiNgqX4RCoQF9zxmXw==,type:str]
      - ENC[AES256_GCM,data:5gsUos/TLw382hx7mjC12Y1hBg==,iv:DiTtnAg5S9Cx1INVd/B9PZr9jtJV75y8PC2oULUQU1A=,tag:1Dnpzb4lzXJl+zCL0D1O5A==,type:str]
      - ENC[AES256_GCM,data:hKbFzEzY0f4ouQ==,iv:1/4VRjs9S3Bpbe8kOICah5dq9PvkTUXUXTb43mr5hPE=,tag:f/CYegbV0VYL/7NPgZZ7Fg==,type:str]
      - ENC[AES256_GCM,data:7NJnO1C6p/eT,iv:d2MTLxzSTtxB5cGBzH4uk1d/jRgy3j+IscDlttTuypQ=,tag:J2mJfFQA8rSjC9trHR4AAQ==,type:str]
      - ENC[AES256_GCM,data:2E0RAA==,iv:cNZ7JAISOz1kiUl61MK4/M9b6yKsyhCcGRZ/HCmgZsE=,tag:uK3aLjAbDpPefn/CrTPfLw==,type:str]
      - ENC[AES256_GCM,data:gImt3on11DcHwzqqTU4=,iv:sQCIbQsXPhpMQfq+DKir9C1/dQRnDsVY+RlELw/0ZPw=,tag:Ko6tabyUSt+nOCyMMXwwEQ==,type:str]
      - ENC[AES256_GCM,data:RrLw4A8EL1D2Yc1ob32H9w==,iv:KwzcG61q3vXXFkvdbKHyiF0PYOSZAHiJUxUZWP0Ug/s=,tag:Fu5rhg8lYTLHOKo7frengQ==,type:str]
      - ENC[AES256_GCM,data:EwrO/Q==,iv:FJV1WcFG6j+CyX+TR3miEG2YpconlBcUr7XCnExud4k=,tag:FQ87KW6gjxS7EkZ/jpRKWw==,type:str]
      - ENC[AES256_GCM,data:f3Sn6jSy1ZKbueJqC9yqqBdLVg==,iv:ruL/pwwmuuDfjIoN+GZREz878B2TBFbQy2LUSXKMGAk=,tag:7g2tEnN9+vlbW3aNTXEvxg==,type:str]
      - ENC[AES256_GCM,data:3n7zZj0wMIqTu82tMBGTxg==,iv:MoKD96d2OpcxjW52bbw3xiFmPjUDhCZAvrbYPGZLqsU=,tag:4+y5gO023/w7gznX3DAC2w==,type:str]
excludeRepos:
  - ENC[AES256_GCM,data:Tlb4rwJE/BUiGfvE+OU7,iv:aNM9U+UcR7jXfptOovGUzXEC5tpwDgps0q8bwnTj/WI=,tag:2yDNVK/XFPFQxzBXNn4bhg==,type:str]
  - ENC[AES256_GCM,data:YMWVGtLL3A==,iv:Bfjjt6t4/CXg4uuJJh9P0W8c8D5BaxsoWPe0QjW5kfc=,tag:dLAr7rRb3glmSFIogQRtqg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1hae0mml9ktpyjpmkcfahpzhk2xuckyn2gnw8tr3a6y6yz8gv9qyqr65n9h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHT3RZWW9kalh4aGxpdjQx
        TkhmMnd2VHRGVnNEcFZhUnNnMU5xTW9ZcjBVClEwZ0t6Zk1qL3NXTkR4MjRsbkF3
        aFRsMnhVQjFCZ2V5bUVqcjI0Rkw2MG8KLS0tIGQ1UFIwbmwrOXVWRndYTGV3RXpD
        NEU5UG9BdnZ3N20ra0Q5Z2RGbFV0YlkKCuJSK/frHyFF9pduBj6mmbn/5oGRZEge
        OL1/NlkDmjsMiwqUOAZPIAJ6lj764zoZ4uIRyliVhhjILFpfX9d6Eg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-10-19T10:50:14Z"
  mac: ENC[AES256_GCM,data:zAgiBDH4L5/EMQjNdeyQiOLv/ZZc8TC/pylK/ceUok0rZSder2+2xjkZV2tSMA7tSfiMbrlDaE8OezkRkcj64GAZcH4Z1Bi7Fjost31uDJNjeZwhpFLPc9OGrj31uWkUOQnaAmSx9tbtduH2M0JwHW3vjt7vGVB/c2ZRBd5D7fw=,iv:/aLR+58AG8CEFRmFkrH6YOqqsp3ROpfzHTVIJfR4qIE=,tag:EHjaOsn/4lQNqOhaAxRBMA==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.9.0
