---
privateKeyFile: ENC[AES256_GCM,data:cZ02NliNE+/Ci0mZuskAFSI=,iv:Q00ZHd2nFLzCY1sHcOIU33herzEJVSx1OkbGc4r8Mbk=,tag:8I96jqyWzNRHr52igQptbQ==,type:str]
workspacePath: ENC[AES256_GCM,data:kk23rFP3,iv:62+OtM39FsqoyoXxrzQQeFC/2PM60Keo6Sedo7+eJb4=,tag:L3zJoELDGfOsczZDgpx6LA==,type:str]
gitUsername: ENC[AES256_GCM,data:cxX8mQYVGak=,iv:X6ncs3vhcIEPmM1ELGR2M7Lxy5hL2hesrI7bticy9js=,tag:3Xg7ZkUYNy8jGVRk+yRbnw==,type:str]
category:
  - group: ENC[AES256_GCM,data:Jwj+cov/YA==,iv:p1MA7nFsjzCe4qTa3thbOlGIjb/KVpCpubA5/4sacZw=,tag:Vj0yWoEw9aErxIX1TMRUcg==,type:str]
    repos:
      - ENC[AES256_GCM,data:4ULnu5Cn/V+y0mTfEk+emXoTDPQ=,iv:wQ2gVY0gQPb+TKacJHPi+UvzqSc53lhEYa6qk47LTLg=,tag:FG7KRGQAXo848cq3yNz98g==,type:str]
      - ENC[AES256_GCM,data:+paFNvMy,iv:ScoKuS+MLwcg3N/ho88ZMnwriYk/qQWl+yp+sGUfxLc=,tag:5/fDC1eRsHH50t3sa517xQ==,type:str]
      - ENC[AES256_GCM,data:mv/pPUFYBv7V+gQU07+cBi8=,iv:IPuLeT56fvzZAo/NaxH2UfMnmvzf4qRPnCsTF3Mn/Mc=,tag:lR86sGlD+IEV5QsRfoI6bA==,type:str]
      - ENC[AES256_GCM,data:/iSa3lTtNM1VKOPzm+h6T6FgTcU/,iv:V6AjJbS4EppNOknphxgwVD+w7ylEFGfw2sIZ/7h6hTY=,tag:erUD8wCeKZAFBCRtCSUYLw==,type:str]
      - ENC[AES256_GCM,data:faH5/cYt8NcFuH5TFqB9,iv:r8eb5to0FsMnqzctnOju+sB/lRMwHk0MP9MURHUdFxQ=,tag:KevopkBLBUoT9M98Q3ISng==,type:str]
      - ENC[AES256_GCM,data:MfMb2j0j9w==,iv:qHn0lCwzmAPim9aBofpnN2LUpGkOljfcS9aIWqRnYAA=,tag:8FsvMDwRhobIiFIUHy+8AQ==,type:str]
  - group: ENC[AES256_GCM,data:XUYVMmM=,iv:tenpyJ7rl7gi5sGfYzFsx6cRfDH6QPscxNFE8t0EKdM=,tag:3MK8PHmdNzHL5GH46lBdjw==,type:str]
    repos:
      - ENC[AES256_GCM,data:2QRpsPWW+D/YuA==,iv:PHsYbMQJ/1ZqWWEZLs6cjX5Bcvy1wOfiNJniUI+wa0c=,tag:RddiI40IPzJ6YK70i9wYQg==,type:str]
      - ENC[AES256_GCM,data:DVfOEy0dpWE4Q76JuQ==,iv:nHObQTDAh+dWQUXoDk3srJTGj8qiJI3e03vfWFrerz4=,tag:ZzeomfEJE9SrUAfS0heWjw==,type:str]
      - ENC[AES256_GCM,data:C4UWcg==,iv:k23gq9B/Aj+w1+8ruTKwFJOoy4gU3eBCztCgfehRpfY=,tag:suDDjZbyTevmyeOz4Xl2RA==,type:str]
      - ENC[AES256_GCM,data:iVHt+NktKyXHpBw=,iv:70JCdAQiBsT8M4nT+z0VBBbVYxTD50BgjWdX4EbLtlg=,tag:YsIcEWWumsvCYKlGLG6Emw==,type:str]
      - ENC[AES256_GCM,data:in4VTIVE8lATMRhHyA==,iv:tAYn5q7AqYTbi1P9OEmXstykH62SgPft48EDtCwkRgA=,tag:39xpAra0AMIFtonh31/aEg==,type:str]
      - ENC[AES256_GCM,data:3qcu8J2wl26qLl4=,iv:JDOzxiIY5cCE+DMbzbhCTRRjLGoSQwGSuWGtNTx/JGE=,tag:x2H82f7XcUOjGJv2HD04MA==,type:str]
      - ENC[AES256_GCM,data:yFX2CAW9QZY=,iv:LXkJP2YjsEfq1EJF/5LEx475Rq2twAwtph86YXjDYQI=,tag:FlbC6yW5bIH3ex/ACB8yBQ==,type:str]
      - ENC[AES256_GCM,data:8YI8dnRxlwBNiOI=,iv:W7I5bZT22bAFhH+nw4dVl0gSzyiRh5Prfd+w2U2dKA4=,tag:0Thjt+qXGnah6aK0RhIC5Q==,type:str]
      - ENC[AES256_GCM,data:gy+VPypq,iv:qzaj168W8dk2/xyyGOZNqQzQRtWUmOMyImL6LkSIDGQ=,tag:SWujMh3zFj/ZgyY0W54KxA==,type:str]
      - ENC[AES256_GCM,data:Ce510QF3UlAb,iv:9l7I188KXt0x7R5zH5GbEoKt3Bk57D2bWEafGLgG9CY=,tag:WruIhYK9CpjHMX3sRcDaLw==,type:str]
      - ENC[AES256_GCM,data:bmnqvilTBI27itI1DvQW,iv:hfW+7l26MkeC8OGuhyPlPvAxeagZ3I/7dEcC3QVuPWc=,tag:XHWDI8ozATMI0v8h2OPiMg==,type:str]
      - ENC[AES256_GCM,data:6BNeBeOJy825p3E=,iv:SNzB7lIW4m4rfgJnPJShHxmQ1EbhhXanzTVpYiRk7kE=,tag:5MML1cjencLFJCcpqVblJg==,type:str]
      - ENC[AES256_GCM,data:iVVk0l/8VoXXrTjBqfN5pkT4swoHaih+ZkYF,iv:UVd4B96xDfs0b/y632zEWbvkgy+pChjhNp8yXCybl1Y=,tag:TjDRyJd28dclvIybkn6fQQ==,type:str]
      - ENC[AES256_GCM,data:5YF1/8IPxx6RZ3FLpA==,iv:3c7qtUEsQWmw6euQbQW76sp+HI7quAW3g5lXutlQYnk=,tag:+io7GN43G5Q7qiveNZULTg==,type:str]
      - ENC[AES256_GCM,data:i9ELh0l2h0TAzuj4y8+w5A==,iv:ip8QDMVOY3xr6gItHoD8tT50Slbj+1VZL9FyGCM9bxE=,tag:ILzHLnij0GhRUlVh6pZi2Q==,type:str]
      - ENC[AES256_GCM,data:HpwJg9YId+H5dgU=,iv:Z79ysd1BS3S9KjUrGTiQ5ceqB7bu0WOqyuSb7m0Uwhg=,tag:vtBWW9aDPTHGo3BGg3yK8g==,type:str]
      - ENC[AES256_GCM,data:OpEMWGV6MdkRsJIF5m/ElA==,iv:hsDq96MKmWv4mZUVlT6C86KOBjNiAQ+KTf+sjUkJJCY=,tag:4RwVsZYZ5KLY7ffvlwLWJg==,type:str]
      - ENC[AES256_GCM,data:8NryQZWcvZHI/DKe2eMDyg==,iv:X+j2UT2DY6u+/p3U45wKSkRClAMGstz2ST3Lra4G+UM=,tag:tNKDZqXT4GgXcuEmtSLsxg==,type:str]
      - ENC[AES256_GCM,data:P5LEAvRMNVB/zxzvcGk=,iv:m12qyYsngzce6PuSjMpv5oBYSd1Yhz6MTkBdkJTkOZ0=,tag:Fn/V3GcsbYbcB4etS8WZGQ==,type:str]
      - ENC[AES256_GCM,data:wOh8NQ==,iv:tRgoaAJbfnuw++CINhFohPAkXA/ZK74VbJW3f3GvFRU=,tag:ebiFX1YRlXf43IOYTpxXVA==,type:str]
      - ENC[AES256_GCM,data:apyrGVw2vg==,iv:cdUif6Tc75IyQYYLSzeisrusXsAJs2zBXWfewn2HNnY=,tag:miSDw3zBJUQx2AkVxWHlog==,type:str]
      - ENC[AES256_GCM,data:IN7YV9Ct7np57Qg3nCa3o+x8NPBcM8Kz/l9A,iv:vaeFkqqfETrLV3rzuoI4I/IZJZlf0tHOWosPTkCbGwk=,tag:J/k4EP6ERnsh93W0N81NKA==,type:str]
      - ENC[AES256_GCM,data:uUJy1PTmPuiWcyieMRJT0z0=,iv:RxllZ2MYRfOw6AGkp2BrpSSx3WNnDfhxyT6eBHYBOAc=,tag:/U6xj8ub96Fcb7eRfkDYQw==,type:str]
      - ENC[AES256_GCM,data:B8M6SoU0x0QYKMCXhFfGfR4=,iv:hQMOvpAHZousYoHkYChm7ENjy0JzhUB+1U4Vz0d5O2M=,tag:xx1v3HV335d1hf1M6VeJ5A==,type:str]
      - ENC[AES256_GCM,data:e8i8Z3/KWGEt4Z5Dl9+M,iv:aHtsEfnuSylrUIVwJM5rnmQTXYpbMoaj8L71JaZrE6c=,tag:kwHE0GXc5giVXRgww8IRqg==,type:str]
      - ENC[AES256_GCM,data:kCyJdXYK6YpdinFCc6pdEgI=,iv:/KBd7qgvAh8GHWuUs3oBBoxwLxc89OYfJtaKYTYr6zg=,tag:6LdRuI1HhI6PEdpvR+601A==,type:str]
      - ENC[AES256_GCM,data:1osCXU/56FPcFrMfZQ==,iv:7cjXI0ItIhD6Sqpp8jUFk0GWd5icKozBDWNOxhEtLOQ=,tag:62YbxO4Nm8e1cSEGMnv5qg==,type:str]
      - ENC[AES256_GCM,data:83Ug2708VmmW9uBGSODm2b67,iv:irUwR3wA3gJVc+BfKwVhv9Bt3TCqI2wH7jAfB9NT1/c=,tag:6UqkP2gOi+zLmowUaNkzJQ==,type:str]
      - ENC[AES256_GCM,data:WNGEx84TZyh21wE=,iv:2TKCm+WUuX2mVpFSBqsD0E1HrX7N0sRhLy0gwIszvKg=,tag:Ay+eXOepdfQFNmgiEHXY8w==,type:str]
      - ENC[AES256_GCM,data:rN3k,iv:8W4XiporU2IsFKLsQsZGpM+OszX6ZvxoIcWcWFGIKao=,tag:CXQ2yIfEFyuX0lcX0WoEfA==,type:str]
      - ENC[AES256_GCM,data:Jl2dNjgLinbV,iv:g31tqUzmDnFbeFZrs9N47xIFLz9JtyDYfLrbQr+Vyxg=,tag:+qbPxe2lKl8cL3FU5tmjiw==,type:str]
      - ENC[AES256_GCM,data:Y4iY7fMzG6M=,iv:4At/bBrJg7vvnp6MEDS+0Bd0z/rfaqNCN9eju19irT8=,tag:d5C7EbXMtAc25B/gAzytgA==,type:str]
      - ENC[AES256_GCM,data:qEqxR4ijTw0a,iv:3qvVKgMrdFXJB5bZKjJ5y6T32xuo71PHT5N8H/NpLCc=,tag:aUimAIGHTft8EfsH/BJAUg==,type:str]
      - ENC[AES256_GCM,data:+fWPCXKMn7W5xA==,iv:YbMnJLtcETT3kNkLRX757emnAkI2zoEeZD4yfuuH5Gw=,tag:4/xmdRtslmw0mwi1RLRvWw==,type:str]
      - ENC[AES256_GCM,data:XgmH0efCv5kC,iv:2Ezij0lWOvLiM5PEeTkJBSBZOekqQHLYk+fAcuoWsgk=,tag:RX3ZUQiHumEB5dBMe6SBUw==,type:str]
      - ENC[AES256_GCM,data:jfMYYZJWQfmNXF8rcQ==,iv:6xUPdGL6NXxaNHJ/Qu691yCPDrPZazj+PWW152+Bm8s=,tag:tyUhbjvEAdOtHYDY8AKqUQ==,type:str]
      - ENC[AES256_GCM,data:DTaZXA035l16IJk=,iv:Ye7lbJxybMaGxn8/eIZErlGlvs1zI3GhyUBV+P2aPZw=,tag:rajmD99jUmmv1ovqLq310w==,type:str]
  - group: ENC[AES256_GCM,data:HYM=,iv:eLAPMwtsqdqFQAYU52CEG2Mdqki58lNLNbHTcBegzwI=,tag:kmk7ipvLK+SMUdKLpeeFoQ==,type:str]
    repos:
      - ENC[AES256_GCM,data:1vEB,iv:pf6ne0CSBdvjZrywISjlmvWu79ZvDLyTbqAbxjGaG0Q=,tag:ul1ncU0xnTfxQiNk7waxJw==,type:str]
      - ENC[AES256_GCM,data:A6vxcIadS427hOmcJ8rPlw==,iv:RILfhPQ1fOXV+vSZpMXr7Mu/Up9HosAhaYgYder1lyc=,tag:UsLeB/z3610/C4XBxK4/sA==,type:str]
      - ENC[AES256_GCM,data:6IwQ,iv:xBL/7YinCm3vgyeDrXwkweommW2FQcZphBKcUbGkN0E=,tag:28BDVzuDS0SDXJ1SZrX5Lg==,type:str]
      - ENC[AES256_GCM,data:FGkYpDJ7,iv:0NLzUrugiOhUoFSQyi7FHDymExQeELT8+opE+1qWlc4=,tag:tQIHFZ8Oes67/MbrSH4Kcg==,type:str]
      - ENC[AES256_GCM,data:6BdBWHHMuCTmcP1OXuVg0ShVx3VqFXK0ZUjwRFL0uvU=,iv:haQu/9bcLBaiFddJPyqdk6jAFfcYCnd/NWkFwUKpO4k=,tag:ru6+X/HxupjLbQHA2Syvng==,type:str]
      - ENC[AES256_GCM,data:VMJ33h36,iv:egBWpAmTPsDUU/Olf9ElarobiaKqtHsx+qOE5BPxu5o=,tag:eOLnHCboydKHEKZiL50wtQ==,type:str]
      - ENC[AES256_GCM,data:sd6JLdQKMM7rmBWS,iv:kHYjOg+R5HrQ7l4ZC+/Vme5gAWD1ILoTgfRDWhzRBKQ=,tag:wxI6lSI0fZk3pHiJmk8esQ==,type:str]
      - ENC[AES256_GCM,data:IPYvopGBLQC1mIlxh94wvgVkTyCB1A==,iv:Vc3QP0rWo4Ywu2KCd/GMuubR7z5MCtvJUnQzHxEkNtM=,tag:mm6Yonw+9rjYDcw8zwDEMA==,type:str]
  - group: ENC[AES256_GCM,data:hGajmj4=,iv:QPXUHZhn8Zyo1Sy+bPyK7U2ux2QYdFbJoLbX4QDXgdw=,tag:9REJG1YnAYqkr1uHHlZ60g==,type:str]
    repos:
      - ENC[AES256_GCM,data:bRHhI1mHFpol,iv:K1EgqVgjzrWyeFLxaHLgd4Zn209iOaMqyNoTECzhSd4=,tag:aOlHOj2Uw022u/+2U1zkrA==,type:str]
      - ENC[AES256_GCM,data:4Ec0nYM=,iv:BlXXIUirV6R9UG5c11luO3KOLt01ihXFALbNtW1KnPM=,tag:GG3LBV8jlRridtXs7u9Tug==,type:str]
      - ENC[AES256_GCM,data:uPYIRfoU0H1/9g2D6Ek=,iv:FKIMtN3TpxXp8XeXjkLXqcxPGQhXmfrykbKWZzNjR+I=,tag:7PkQFt5cNgYX4M5KjV23qA==,type:str]
      - ENC[AES256_GCM,data:RnJlEn7xM5vvRw==,iv:X3SfTqUGZPx0NrG1nekT+xi8RnLob+OEoNbY14YviAA=,tag:wsZP8SG8kCUpvFFAmUb5FA==,type:str]
      - ENC[AES256_GCM,data:o3aJbWoIM+ijTOa5xQ==,iv:85iiU538gRx5w4l+6IWepxHttGf8LmkpHt3OjEgenPk=,tag:8lT9hcOwhQgW0iBSyxBYQA==,type:str]
      - ENC[AES256_GCM,data:Vic1jA4ZF+f5LKJLIjJsIKi4LtnP0TDY,iv:Z8eXiqMuYvrfU2UBoKvVLu/OyIyV5qhKxxCI773VLTE=,tag:AoKiWxd0V/rRI3OYxI7dgg==,type:str]
  - group: ENC[AES256_GCM,data:t5qrzq8CUK8=,iv:Hylsr6ZHc6f4c1Lt4tRAgX+LR0swutfIm95goeOgyzc=,tag:O3Bt2hQcz0P3Js2yT73QeQ==,type:str]
    repos:
      - ENC[AES256_GCM,data:vzK6,iv:WKOKvpTEfIdzEimr0LfGDmHIb/auUJ0y3DUQHg9weYs=,tag:gce07dx2Rqv+UyD3fYa68g==,type:str]
      - ENC[AES256_GCM,data:cdj7STC3DRsORs4=,iv:3/Eo0ToMXHxHNK0RfEMX81XAcZ/3uKC9EwPnEL13yeU=,tag:S2YpDw0pw0h3H377G3Ox8A==,type:str]
      - ENC[AES256_GCM,data:rNNRl5RhW5wsHAxySWA=,iv:2RuPAikssBXwdcq530zrQP70J+ZaIZ11yfc6TrtmOqw=,tag:5h3O/0b160gkP+qSw2j5tA==,type:str]
      - ENC[AES256_GCM,data:FwgvjmyY,iv:8sa6f4uMzIk2BQoo9247wBEeki/GL4INBFneSKwqhXw=,tag:X1V3LAx9KDu10ztntHRf9g==,type:str]
      - ENC[AES256_GCM,data:lM3BDdv0dZnQzPoK6if3IQ==,iv:Pq3hkxy45bcTPWwy2Kztxfi/31/zezhf8UY6BTCUobI=,tag:QRHdj+deu2YbKqpFQeHTXg==,type:str]
      - ENC[AES256_GCM,data:UbGc8Y6i4nOkSHKTbQ==,iv:94vNP5rsIgm0/tsX/zHCDpyx9+RGAB3gxZuyI+0t/FI=,tag:WqIXUZLSPPMW0Uw7fwV3gQ==,type:str]
      - ENC[AES256_GCM,data:fD9G3R16CMdhFsDhIisnPYPsZ0GrN4cb2Q==,iv:LC8Q8bLkMyPhP23OsPAxh7A+mvusS5RCmc3JyPY4XXw=,tag:QIC6qusyZizogG3Ii57sAg==,type:str]
      - ENC[AES256_GCM,data:kqNs/f/V/wkrCmo=,iv:5ZpyEeigYeTmM5qSHlQE35Dplp4fraaqTE+1TIgcrEk=,tag:3X/hAuDoZvWtnqDqVN8YWQ==,type:str]
  - group: ENC[AES256_GCM,data:AlwMKT3/aipzSQ==,iv:hY3IrOXUdHk0JNvySSx4wPILv8w4Q83Fi/yjs5a5N9w=,tag:F901jk9VvJKSjFt+IFPeCQ==,type:str]
    repos:
      - ENC[AES256_GCM,data:jeQfkEznNzTZaszFWj/8uUbNT4WtcRzIARD+GNj4T23j,iv:hJS8LacxdutyZDzO6FQPNygIWDotXZEvosRO24Nqrrg=,tag:BWicDeQPGPkBXQG53sQh9w==,type:str]
      - ENC[AES256_GCM,data:Q7eiKHDCH9j6vG4DyGh4,iv:e4YWNSroiKwuelw95PtLQDp33pyNCTSJzJk3BMt8ReA=,tag:c6qjGZZmBtPopUqBNjVSdg==,type:str]
      - ENC[AES256_GCM,data:+5saHc4qUZrAsViRDjx8,iv:CNpykRk1YH1psSf8OsBgpZzcC18Ny/EFeoM+BhKREzg=,tag:dDQC5ia17yFy7UONFo1Uww==,type:str]
      - ENC[AES256_GCM,data:aNE4J8IsY/ugVCQhnqiB,iv:cuwyjs/BE6TDUBhZLOTQeUObjzFaMujfJthI/Udv+WU=,tag:hq2BD/loNsVMGIo63Wis/w==,type:str]
      - ENC[AES256_GCM,data:dN+yArimuihg2NN6Voxedm3f,iv:awqFOvZ21eKPI/qxn9WP4R3Qg9Vt6xQittiR4APCXRM=,tag:Bz3jq1wNdjh4vnr337luDA==,type:str]
      - ENC[AES256_GCM,data:d3ONzxSeoUdj70jqpfaKcA==,iv:ktXIRSsGSHfSmNz5hYkTnqtTjFnKjVlZlVrnhEK2SSM=,tag:veFsYyPnJgv6lh0o+zGRUw==,type:str]
      - ENC[AES256_GCM,data:ibiX6hmDK4RriAwpNxx3PBQ=,iv:NUygDi0ubWW33Wxmd1PLjJkyCOpqAVw/KaNT5exo67I=,tag:C1053h/2VzKE7QX8rbRUiQ==,type:str]
      - ENC[AES256_GCM,data:goPBvlX5a5O/gyMGMw==,iv:Ofija0O43X2/eLEZjXFaNPoUisUTgwuxuJbdjc0sXpU=,tag:g94Z9s1ieKFPM/d1hCRJCA==,type:str]
      - ENC[AES256_GCM,data:Cx7PYyIk1NPGfhbfMg==,iv:40SqUz0px/NOdjYb8JeG+k33fhefd7ZHW7ieJrSm6mA=,tag:oFF+xvrRzRAV6+D6LEJI9Q==,type:str]
  - group: ENC[AES256_GCM,data:oSUc665LCbw=,iv:5n1FknPqwTY5vjxP7MsvDHt1SmYb10BFrQu+Xjg2NMY=,tag:gImNwMxPHf1A1kbugOqraw==,type:str]
    repos:
      - ENC[AES256_GCM,data:ygJtu42M1n07DJe0NCY=,iv:Yl3MxVEfSWrEUtveqJOL5/x989yc+O6CeXLKd0QZHew=,tag:VoP+OzNGFRsdE1QVWarcWA==,type:str]
      - ENC[AES256_GCM,data:BsIQoSJbaA==,iv:pdyhZYIJmUM8xrU00nykv0MDm/BvpzjC9jekIy3bsYA=,tag:z8a9uRFeKOv0ZwHM8H9g5Q==,type:str]
      - ENC[AES256_GCM,data:y6LCiv8G8CaEtySH0w==,iv:QQTpQf3yhzY5H6jXMVSHJ3mV15PyidEgk9WX5dMJer8=,tag:0xo2P3aYbJvAH8dTkGK/JA==,type:str]
      - ENC[AES256_GCM,data:Hf3ZOe84FPJLe6idazUPtcfNP5wm,iv:IYsnlEX7AjPZd85oAIw0Oxlr9w/KXqaZ7X0OOhEs6o0=,tag:hRbhh/WOpz+4VhdV6gqXgg==,type:str]
      - ENC[AES256_GCM,data:Nzha8R2+Y+cOAnKLQIfksrBWmQ==,iv:5yVslWtEttpw0TJjVYSzEnrmqJ4FwO7wG+Ou7RLp+xs=,tag:RomNuYY77eMTz8dXI9ezjA==,type:str]
      - ENC[AES256_GCM,data:WUWJ9eL1QSMAyWAj3sP+9caRdwrU6O8+JWY=,iv:kiH3TuNe/X1Hr5snpfS81DTIvzomBBd2E3IMdr4jJlY=,tag:tHVl2YA3mizMYyeyqjGIHQ==,type:str]
      - ENC[AES256_GCM,data:yAn1c4s6AVE+C9Rw41+rYdrDrvbF5Q==,iv:tN20MzIYS9AnDIoST3gKrSCxIM21+tc5CLdnm218f3k=,tag:q49CYJ/yaJsdMV219qmMYA==,type:str]
      - ENC[AES256_GCM,data:i+IS+kRmLU1genyQNh/xzk1sFT2pmR6bfBOpI1CrQWQq,iv:763wEoNmqUVSsvxaSVqjoZBQ33grQyy6GpA6+pCMjaU=,tag:EHX7wOTHTC3mjw8OgRfTvw==,type:str]
      - ENC[AES256_GCM,data:KIOELZuudo7Gebx+,iv:yyBmfPv1p7oLEIxytcadB1NQ0/DCEOfBBkHaH6bJSTY=,tag:HQzTJUeAdAknNHun0Z7IKw==,type:str]
      - ENC[AES256_GCM,data:BtWouUPV/19AB7FJ+BJuo1D8VR3wxamcDlIvzRfh,iv:Coiae3AT02tXCNpi3eM1wvDhGjNB6IuJFdGkIvoovyA=,tag:n8r5JAAvSk+XSnXf5jrUDw==,type:str]
      - ENC[AES256_GCM,data:ihOFD81wTMT2yL/oHIJO7ZWZduznWVPuW2PAz8w=,iv:A6WekjUfPHsRjUolCzF8H7mURLIS12CZY2AUlzkw8CE=,tag:0Dd5dqN8m2UzpG1vEJHu+A==,type:str]
  - group: ENC[AES256_GCM,data:z7OD6vo=,iv:PkIEaQw0uI97um+LH4jBzSgSVbvPrwZ8KsxXexOTczc=,tag:F5K5TK2OcefaLMsbAzZwdA==,type:str]
    repos:
      - ENC[AES256_GCM,data:YJGNwK2lEMFgY0Ck2TVU8aY3,iv:YxkUXNrv1Xoy0uh9lLmMEaP3cYwghVoGCKhigaWC9OE=,tag:qAG/Gu79V2W6J5v11xz3ug==,type:str]
      - ENC[AES256_GCM,data:Z2LPC7BiJhOTbds=,iv:jJ0VkUGBE5S+w3kGMCp06vAP2JqpneXUECqlUBpNZo0=,tag:ywNo4lNX5hiQHvHjPIt1fA==,type:str]
      - ENC[AES256_GCM,data:OlE28UOXCMLPFA6g9w==,iv:H2zcdR1Bo8pHottqvFw2JZFfvxLIsnaZkUpGGU9KJtU=,tag:+z9PHlmQEQ6xBHGXELdhHA==,type:str]
      - ENC[AES256_GCM,data:0sklOE0BiGQ5Iz4=,iv:or4kEKUbiife2hqjzohrGyWN8bgZ4Wv22Pji77mKIA8=,tag:vgK0s6IGlrHTs/OPSxtKBQ==,type:str]
      - ENC[AES256_GCM,data:qqAWI88BI6Yum4Uv67xfPr6Xnw==,iv:e7W0LJ2ZsHPNjlWP+RV2veVN5ROOWQv3H+Mxy5kBJrs=,tag:G2Y44eRGgsnpnUHHfVELXg==,type:str]
      - ENC[AES256_GCM,data:O28TD0BY,iv:rKEuF9yiEor7S2gMK9kUkDVPNnIHb1eYCPakTHPs0Wc=,tag:LWwh2CzVE3D0BX3yZ/pCkA==,type:str]
      - ENC[AES256_GCM,data:HIbjJiH8BBMaUfv3Po/+1xy5fg==,iv:AprPZHqaUzI5R/GMRzhAt/9t569OhTVyJ/dTHaOVapI=,tag:QNFx092MF+vxzgZT5SrM4A==,type:str]
      - ENC[AES256_GCM,data:CcyA32Wz3KE3DA==,iv:bTW2N+fvyrkk0FuaQF5HJDbL9BMWopYu/viDM8/NVMc=,tag:7cRYFwgWRv8PkLr97zW/Zg==,type:str]
      - ENC[AES256_GCM,data:iMDWFSDiTyD1,iv:arDAe7yh4+d7n8VwBf9A65MNUASolhoB/eB88pfuGBA=,tag:rBO6EOPnO3smtB4GzUZSDw==,type:str]
      - ENC[AES256_GCM,data:wvRqYw==,iv:FwtOK2f7ZPfkm7es4yCPW4T+rACfNlHc+JdrUGhIPQA=,tag:Tqw0R4tkvqxjeGI662RTwA==,type:str]
      - ENC[AES256_GCM,data:BrtdF7Cdphaog+CvW3k=,iv:uawSilYKbbk2d1PCRUB9D23EkSBscBJ1cWxfH6eWJJw=,tag:i/1ybbruE9lIkpqHGfPgaA==,type:str]
      - ENC[AES256_GCM,data:VOtHpPBmRrjrOWuLCD8mmg==,iv:rP/UU4g/5s+rT0D+ltEumaOLzVlPKJUJ4ybPpn9zGs8=,tag:xg4TIEgNiG0knr0+a+6e4A==,type:str]
      - ENC[AES256_GCM,data:oYcuDw==,iv:Si/bmbCpaTPk1DIfI3tch8qVFZMZKoUQw75MXLHELxU=,tag:mzvYx/mejXTZRqdahtiM2w==,type:str]
      - ENC[AES256_GCM,data:xwz8xGeIuG3H11Qg2euwcs7MVA==,iv:NGZSJRAA/XOgwzLXSZw/Y/w52Rw2ZRL1PaXS9k4ZIPs=,tag:FEY119R02vdcxVZr+/1Pdw==,type:str]
      - ENC[AES256_GCM,data:2FM7IL+ap8tcKwPB4Yyt9A==,iv:BqK/n+N1IpUc1uHb15ezccrgx8MSsVtXZEsZ4qqco3U=,tag:9tIcsayPS5BNolNyisuAvw==,type:str]
excludeRepos:
  - ENC[AES256_GCM,data:6q2IxYA5GjRXaz6hyn0O,iv:TduLEl+pTTXRcx58ycG+RuGbUZ7yVb/817pDcOxffP4=,tag:ScHymjlgI45QbdXhLi96uw==,type:str]
  - ENC[AES256_GCM,data:slLULIf41w==,iv:kj/u/UQlJ7dsmNRTpQcjOjC689wwTUOF3/O1gsCmVyk=,tag:wwzVtI5h25bytWV2JgTS6A==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1hae0mml9ktpyjpmkcfahpzhk2xuckyn2gnw8tr3a6y6yz8gv9qyqr65n9h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBQXdWL05aeUtpRkNrcUo1
        M1ZDTHFSakM1QU1hZDdEMzNwNGs2b3hXc2pZCkUreXh0bXRnM0diZVFoVnljSTJ6
        MmV1MkxOdnhiTXZEajQxQXlFU3lJaE0KLS0tIEN0d091K0phSGxGNHZURGtrMnFL
        TGR4TWk4LzJ0WWpPYk42Y2xyNmY4V0kK+Dr5sYgvU/LzQot6FQJpXVB3nDNFsk6n
        qUXPMN4JnvZZYvPHRKSRTyZRcFlVytbySmdPneViv+bgcf68Y9B0mA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-10-19T10:43:13Z"
  mac: ENC[AES256_GCM,data:MIJCOvrHukNk451QVoW8s/7qL/VAsONTyuF4xV4Yvk05otDKc7ii1H9e4l6iohPtiOZmmiX48u3sQ7qEqlbNfWf3heWfQ778E5kOTcSXZtLsjhs1uZvV6SpuLsJKqaLBfaPGLBi900zSorf9KD6mXUGvhNfm1hNJ2/m/YqInp+A=,iv:CSOwhNxU5M7jbeEjLB9tNCUOnwPIOGbjRTfV3tHKfZA=,tag:2Lth4uIN+j/ahrnRoackjQ==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.9.0
