---
privateKeyFile: ENC[AES256_GCM,data:8o9puducPGc7AxL0RP29PZM=,iv:NeEuirvgXA/x9k8EXOnf3XQstKtaKKRA+VGxsL7CoC0=,tag:FzVpkR//mD9uJKYmWbEZPg==,type:str]
workspacePath: ENC[AES256_GCM,data:HbGcuMyb,iv:iIKHh7Zrnb5O4BjDa+pulN8SKTnr0lWwzSZhTGQ1/Lg=,tag:tkKlK2hS5dnYEJvz9gV5nw==,type:str]
gitUsername: ENC[AES256_GCM,data:Oqm/uRRwDxM=,iv:GcXtKhKuZRIDYXRPFsTEA/9NFqnoRq2DE7oHqaVbPzA=,tag:E2krYI14qRKJj/UtvXEsbA==,type:str]
noCategory:
  - ENC[AES256_GCM,data:QMU0c0rVeXoL4Q==,iv:PavvSaBFBy5B5hPAEurPJEGGDTiBVhMvCbWt2EYx2Qk=,tag:VKxXNoj8DZryTlcFG2tTjQ==,type:str]
  - ENC[AES256_GCM,data:Vl5qn9r3,iv:iohcqksRaAoaxtx0bUul99AQbO8VO6TEACk+R7jVDJc=,tag:NhozfoeZNSZ8vZu24cBCBQ==,type:str]
category:
  - group: ENC[AES256_GCM,data:hUTCGfYPNA==,iv:foDMAZLW6JYJtGZ0Y0B6VRuMFdciVfTohnB42H3++Qc=,tag:uDz1lF+ahJr1TYp240fXew==,type:str]
    repos:
      - ENC[AES256_GCM,data:RJa12UBJhvZDYqfsxQkHPqhz31s=,iv:oHYgtt0a9puL7l+PC8/Jj4JfUWq9jNlh+m+X/s8ygIQ=,tag:Hs/kqrMY8tGpsi14D3yQwQ==,type:str]
      - ENC[AES256_GCM,data:E1bKTTIx,iv:JXh9h2z7HemXDQeprBdOHz6qhMz+odtlvCAuZeZ96+E=,tag:Pqz4KX+Hvy1WWdUnFC8KjA==,type:str]
      - ENC[AES256_GCM,data:pMxJMkn5bC+ylQ2dC5rL7MY=,iv:iEU8g/9fwx2VSSYMSukSYhhYrN2BFcQ537LzY33DzeA=,tag:arLB+pWADxiJok5RHrOQkg==,type:str]
      - ENC[AES256_GCM,data:0R6ABXbrKN1WaySR8ceFlI3F62gk,iv:PnVMaDHZVWiwg7Jq74VYRHYavO1D5ZSUkBRBcV0dnbA=,tag:xZz66kFqXIpiA+KB9GEyHg==,type:str]
      - ENC[AES256_GCM,data:2wwZ3vHNYRG81ymsOJGZ,iv:qJzCNArkP49ZkQ39jC+rL3OQI/FpQM8C09M/eiPPY90=,tag:GjOhuQz8wvhJrZ+TPvnP7A==,type:str]
      - ENC[AES256_GCM,data:lVYkFI9z3Q==,iv:4c7kAqeESax7G0Dx1CRULJ7EL9dFke5flPh4ze9daz8=,tag:7uNedrXwYJH6bqXXBt28vg==,type:str]
  - group: ENC[AES256_GCM,data:7KMZa5Q=,iv:or/IbzWjl9NbV3/MgFBMU/q0ztQaK78k7OFwsmJoLIs=,tag:d3t2+bOBbWgkXITs0iOf4A==,type:str]
    repos:
      - ENC[AES256_GCM,data:4Z0qoAdslLsdGQ==,iv:c1B7uaOf4jBkG5VHSIgEie9tUwK7OKm139FD6R3HqMo=,tag:5BohFFcjyjqBINmG5fgH3A==,type:str]
      - ENC[AES256_GCM,data:V6Gfa2UCoEAyPl1Gsg==,iv:aWw5IJCsg4Y0hNt1ZJHekz/AOsHC8pXCyhb9FRg8skc=,tag:3sR2TbocHbtWoHwS1bu7rw==,type:str]
      - ENC[AES256_GCM,data:QqNtIA==,iv:fIdDEh+OXtotgDQngzUAf4NpxdU1LM/x3/wDrCKAFPw=,tag:ojgT3X59IEfee4JtALc+sQ==,type:str]
      - ENC[AES256_GCM,data:WWmqHcMxP5cJ3ag=,iv:iBYqWmTJWJeZlIbmxG7a2/HbY/ILueiop3l+lfFZQLE=,tag:aD/gHkts7PntRJ+xKEhIPQ==,type:str]
      - ENC[AES256_GCM,data:0BK1MilIqroQW7Jggg==,iv:f+IDtH2MtmF/tDVmxl4YtKrmVQ67MbegZVr0QQNxgv8=,tag:Yx6ZSQCe687wSNJzyX0ORA==,type:str]
      - ENC[AES256_GCM,data:eTU+gph3unVr8sI=,iv:PbiRqLYw2NBr8Zd1e9uvcvz5lDy+lKOIAaUMGFxSeIw=,tag:Lxlhd0lmOyVd/cv3nwTbrQ==,type:str]
      - ENC[AES256_GCM,data:LhRelm0kqUU=,iv:2irV4lMCd7VbT282t3mvoM7R7vTqqR9PTr5vbkkhDzw=,tag:t6xcNiJFv5oO9nYsR4HODg==,type:str]
      - ENC[AES256_GCM,data:Bkj6faSgYt7XqPY=,iv:fsGHsZKuy6QfaSE/Bc1p0zOkosfjdsN3e1nvm6lSiv4=,tag:I1uKaguffqivdZ2iAkcDJw==,type:str]
      - ENC[AES256_GCM,data:KFXKVv4x,iv:YZKolG6StC5D8P6eEhhsHje+XGN2t0yqkWm5sFDylN0=,tag:ho7igZ/Qy83r5AwPwQad9Q==,type:str]
      - ENC[AES256_GCM,data:0A+fq6TiMrLT,iv:o/v89eZJKzdNfunlcOPJqAaQxW8sIPkwGh/whQ/e9Ok=,tag:iqqz04fjEKsDhOoSnNE0jw==,type:str]
      - ENC[AES256_GCM,data:/8AtRtMAhIrACIITaqt5,iv:ETTnNDOGYpQYrnWLBhVeMelrdssueY1fGKUBPbaOoZE=,tag:87pDCn9CgqsDFanTjAMUSQ==,type:str]
      - ENC[AES256_GCM,data:Pf88JscZqr04yEI=,iv:AMMGxIM9pTjqSabgrIkl00V5zJGMKjXNJlBs36wXqXk=,tag:DH+BYrl87YaOqc2xe8Yvhg==,type:str]
      - ENC[AES256_GCM,data:98SxU6+QNUlJJ6XwrIuYdHGUaW0/xw6VOYtT,iv:l++JZa+K8sUcLrKhaXVNIHMOaC4wobS9Sn0hS13uBwU=,tag:EzFVpMVARRYFmsgn1O1K0A==,type:str]
      - ENC[AES256_GCM,data:awdSkyI9QyUYFPyuFA==,iv:F0Q3HVtKQEE9Q2hSIvPKvV/Nipy/j0P7dSD4/hKobxg=,tag:jz2Y/idGR0oTQFnkILe4qA==,type:str]
      - ENC[AES256_GCM,data:lH4bbG8rOinXp+YbjjSbJA==,iv:WX8nMttlsp5kDjdomq47LDXZ16y4uY61ElUTmruvDwA=,tag:EigpZWXS8o+ie4vWTsa3cg==,type:str]
      - ENC[AES256_GCM,data:DVHw31te6GcjK8E=,iv:3kJp8FKuSHQYkq13K26aZwvN0mAJ6XSG3Y4WxlW9w14=,tag:Brmqnv3Bw6+gHat2sb+bCA==,type:str]
      - ENC[AES256_GCM,data:9FTzMkHg2HsEdALZ5u71YA==,iv:ybSxhY+PrDk6o2UF3gs37WncdYAIm2NPYzkLIpMGkBc=,tag:Vn2oE83q85lRuaskLnnArg==,type:str]
      - ENC[AES256_GCM,data:x2IrjoPnc1T/4kVPQYFEvQ==,iv:ARR6OJqiEUyGXLJIQti4BLPkjfGlEEgdK2h0V98xKBM=,tag:ct8KUe7Ziv9Ev9RKT79Umw==,type:str]
      - ENC[AES256_GCM,data:AnNgjhNwWuA87gY9Sl8=,iv:Enng5kOIc1m942EsnSmEhgsX530OQ4+xOT3xAJP1dAI=,tag:J72jcmo+dYK38WrNVCXRFA==,type:str]
      - ENC[AES256_GCM,data:iky9eA==,iv:3CWF/UOkZEqbfTNF4sKz3KLCL6wMiVj6w7zOXwvqWIs=,tag:2q72cBubwfsh1KHoN9o7Aw==,type:str]
      - ENC[AES256_GCM,data:7OyLHcQdeg==,iv:l79gL68X913T6X3lU+vmiYVPoKBU1z2duVf2ETEIYj8=,tag:0O8Zg4pYXghRm7c6RKZfQA==,type:str]
      - ENC[AES256_GCM,data:gcVKihRpyLNuizwOLEgI8lyXd1SjDYKpqx22,iv:uY9Ui1KeolgCAd3dfN9MzKayhXns8AjNB9/+lXUrmC0=,tag:SbUQg4AU0x0P01fZ5XRgPg==,type:str]
      - ENC[AES256_GCM,data:wax6vIn1X1SeIRtTCg/EEE0=,iv:37+D6vdj5V6J9m6NucBXmRZ0AQBJoRVgEfwHrpYjoBE=,tag:db/RZhAuYCz9q6OXb2hKcg==,type:str]
      - ENC[AES256_GCM,data:jcqnq/XwodA50a2c9xahpzM=,iv:KmpbNmSCU+0TfZLUxacJilNw6XQFSchtp5eYBTrTOVM=,tag:TAuO1hQshji2/YZcIPHEGA==,type:str]
      - ENC[AES256_GCM,data:bWJ2V/cVglsb40iJx6dl,iv:+hw6N7NkwadU5Lqrt2YbhkURspy3D/9mKbA3yE2cimM=,tag:tVAG3nPZ4GLq/Vwq1B2GIw==,type:str]
      - ENC[AES256_GCM,data:9KSiiauubDJXuIK2d2I7Nlw=,iv:V/rApQl4oP9V7zgw1gTq38O+peI9+313Poxz5tX9HPg=,tag:E5BCpOnx3dDAjzIbqY5nWw==,type:str]
      - ENC[AES256_GCM,data:ykSlz64DeNdHT534Og==,iv:FCZpZKWaDR+RFkXyZ6geLvAIJmFwK81sbgt+y4FCMIk=,tag:9Ss1LQsoBtuMV1MW4vJu1g==,type:str]
      - ENC[AES256_GCM,data:/BXpsL96xz0pXglJhJ+oJlPB,iv:ZR0uo7BrpRn5YDdr8+RJWLTbxZ+Gv34beCdq1/AptRY=,tag:S1uIsXMU+F5SeU9fD5rHYg==,type:str]
      - ENC[AES256_GCM,data:1AGgdDgpqxEuhqQ=,iv:P84SjzvEwHjAdOnsRr4Eq/dcdyl4/l8digcXM/gZPgw=,tag:Ok+wCUAMl3J0MsUd5mzfaQ==,type:str]
      - ENC[AES256_GCM,data:qJFY,iv:I37Q70MpQC1ZtohB0XybOSY1Ji4tZuLd2R2ywoLUQCE=,tag:WQCHoGt6mklgJuYAQ+bCwg==,type:str]
      - ENC[AES256_GCM,data:m2jBr2F3IYKf,iv:FJXoBRykYGfPbkfvhWoNQkibw1MeuZ8C2mes3Qib1TU=,tag:tBkyuuqNPJsejIK0ObkGbw==,type:str]
      - ENC[AES256_GCM,data:apmjEtPHGdY=,iv:ZriIp2jNDfQPTNeAxE4ON6X9zcECpI3id92FXS2ruV0=,tag:cOpkgATc+qTDJN/BuOsRYg==,type:str]
      - ENC[AES256_GCM,data:u3xjcI5UaPIx,iv:1y4dgnbIKnhRybUDWWf0HVc86ycB2jM0BIhddc50uss=,tag:n7iwtYmbx1T6QooVVg9hsw==,type:str]
      - ENC[AES256_GCM,data:qHSILelyYcYsGg==,iv:FTztY2C6zNaN/pf+73ADbvIKo6qWVy4oKEagtSQVZQE=,tag:OTjVWiwvMWQsPqxCtoY6Jw==,type:str]
      - ENC[AES256_GCM,data:9HY/R24E4xm3,iv:UrB6fYgP9Lt1bzCPlzLSNZSrWaeZrC3XERW7lTMpUao=,tag:zsMsjoQ73XVGy2qh2ABsDw==,type:str]
      - ENC[AES256_GCM,data:ECH2axVxdHdNfqT8mA==,iv:fI2BYPq5xIv45guuo/ZMdtBQGjU2QcyTUOxpnNWYDZo=,tag:Vh12KqoQnuQEIYHfY4bQcg==,type:str]
      - ENC[AES256_GCM,data:o4uUoF+3aBGER6I=,iv:l7R6YgXWZXCgp9gTKgX4FX6i0NEo+ow8RMqi5Yju+Ho=,tag:BhKH2mPKcLnk43Q+N/Zo2g==,type:str]
  - group: ENC[AES256_GCM,data:8HY=,iv:O4bPmWjvjZ4uJLXMTMRt2WcGZXOluL1nwOfe7ZGBhNw=,tag:xZkrnu2QWMojXNLuJhqgqw==,type:str]
    repos:
      - ENC[AES256_GCM,data:ZxOM,iv:oQijXGGgzJJobQP4S3QaZbqaI6HEOybtoX4S0Ng4OLY=,tag:453tdP6QVDNJ0BLhBzXYEw==,type:str]
      - ENC[AES256_GCM,data:RiInowjmzloQyzjugeWZvA==,iv:No2ziyBJs2/X1vRUXZb25Lu0NHciMOGIY9GnMTslQLg=,tag:+tzathX/klZzcGP6OXf6Ug==,type:str]
      - ENC[AES256_GCM,data:hHDa,iv:EbLFBX305/3mBl4fL6B4Kp3+cgMNe1ICslSxcWx1PvM=,tag:jjOYoGfqvecLxNdguIKm+w==,type:str]
      - ENC[AES256_GCM,data:vZPhHptF,iv:4pihC1NVGerWhwG/iCCEMTkecVzFeMTP5AbHrEqO7eA=,tag:9CVIB+N47EWb8XWa7z07Cw==,type:str]
      - ENC[AES256_GCM,data:o/IqMrKxtl4pAtniAfVrq3KIeJ95oP2Js83I7ygXztw=,iv:VhOmJeW4MnkxHIyaAmwn9/oUNRZsAthPzjLQlsw1viE=,tag:86+t25l8f1vNf7sHSa0ovg==,type:str]
      - ENC[AES256_GCM,data:JHsNyAbK,iv:7yxIvKoSXuN7eY1xQAIAH/+5KDSFLZf3QLxKLrz0L7U=,tag:dgRikMgJbMl9XhwFoYKuWw==,type:str]
      - ENC[AES256_GCM,data:P88bMgIX5pJo9inn,iv:tcEQBqaaCXd2DWF4cNzFPIQBcFvlpmiEy1psuG+ZnVY=,tag:mynQYBZdOMNvzS9VRVptDg==,type:str]
      - ENC[AES256_GCM,data:iHKPoe/VPZ8W3WhKeQ9yuaLBfUnwTA==,iv:oYBXgAKQvsNF/b4SLTaBZnxdS8VqLvtWi5X78nyuilU=,tag:p1UtVktASbX1l0KgOORmaw==,type:str]
  - group: ENC[AES256_GCM,data:Mx3H0UY=,iv:OqYsm72BM6Oo0L2ku1s+PzBGp+HP8C4GjFvD9nDCdfQ=,tag:dfjpyehEhEWMT2bXrvpZeA==,type:str]
    repos:
      - ENC[AES256_GCM,data:4RzWq6UIM7Vk,iv:mwdTUJTU66lklL/CiM83tzUlWiV2fidv6Y65wsXF5Bk=,tag:AlMxJa1RHaDC5qvKWlSB7g==,type:str]
      - ENC[AES256_GCM,data:2GAjiOA=,iv:R4OIGIacHi1jqQ0dZgaaQvYQ3cDa+HrKNO58j2A6nWo=,tag:nVn0pvjUcomNCyh0X13mnw==,type:str]
      - ENC[AES256_GCM,data:B0bKiHcpvuLrD9rriyQ=,iv:z0wEQncOB6txOOmaJ7ekxt3udZZBwdH2SRZ52lsb2vA=,tag:MANqLGzBYC2MoCOgJUacpg==,type:str]
      - ENC[AES256_GCM,data:xWFHTwlrDpOCzA==,iv:Q84r1BFNpeS1KVhRgwSDXxv5lpSYUHolaX4d5eynYeQ=,tag:bFuQTXkhRBgtwsqAtnMl7Q==,type:str]
      - ENC[AES256_GCM,data:+gUbw2K2axq1QVAWMw==,iv:n1ZEFW6e3Ajq1Q4/AhZPSJEvZ4NKueZiy/LI8FL2SjI=,tag:iyKkYiehtk9rB5IqWL0n7g==,type:str]
      - ENC[AES256_GCM,data:d657c1kJN+XhrtOBwmjJLVQEEpYvSk9W,iv:88CWxGGcvTyAw3/lUAK2Lf6jYU5d8e96/JMY4SzSF/8=,tag:XguMuEQhJVXRYUoIHZcmmQ==,type:str]
  - group: ENC[AES256_GCM,data:UeiR1xZlOmk=,iv:Dg4YGre8mvvSlxE6jkV57//pRoLEh8DI+EZZ8xMX3Sg=,tag:g52ame0C6mtPLVAlCrXDMA==,type:str]
    repos:
      - ENC[AES256_GCM,data:d8e7,iv:SADfiZWGfcOY/XniWb9aKAZdRY1NHcm+Sv68dm/nn/4=,tag:50ai5PWI2227tCqdWOpIgw==,type:str]
      - ENC[AES256_GCM,data:Gn4q0YDpYwulgi4=,iv:FGAH+60thPpYKckWpCSjMO2oPNy7rNsRmkUZgKIHabU=,tag:mBrahtNa4ZgYvLSnE2hmgw==,type:str]
      - ENC[AES256_GCM,data:NllT/2ATca/jQcit0nI=,iv:tNfQxRzPLnxfeaqmY48garTSbPZxU63FDVXMLGlHwho=,tag:MpQuy8H1vWUotanM70daKw==,type:str]
      - ENC[AES256_GCM,data:CtCYK3bW,iv:OKITEZsdlT+TYV0YRYDqfLMZQADBeUWU1aW1sSN9mtA=,tag:Kp5JHBvGhGnzKAn8HdH3qA==,type:str]
      - ENC[AES256_GCM,data:ojBk0ceOtB8V4f2nG2DHRQ==,iv:s+yExUk7LbgC0LVweuqMYuXcQ4F464/CR99G+QA9QxQ=,tag:rrW6hQPlFwINS0BSZYaKBw==,type:str]
      - ENC[AES256_GCM,data:OpAhpW+s53SXjDt4MA==,iv:dU0fmY6m6EM/iN0XA5dEnSFrzCA2N0e+e32JsU2kQQI=,tag:URqyj1WBYFy6Sd7zM7qryw==,type:str]
      - ENC[AES256_GCM,data:lVTi/qyB9yuQ0Uc2GKaYq52LqHajpUEi8Q==,iv:AD3Vozk9h6vEZQAWYAggX9yGglFNfm6XS9Phy8dA1OQ=,tag:2gv8+JV7EdlOWt2AnJhHrA==,type:str]
      - ENC[AES256_GCM,data:oR1Dyy8UT8jqR9E=,iv:9bW9z5i8eBUOmOeHrqnNTTTkwHXK8JHi0cbg78T5lRw=,tag:9qw8o8avqK4X+pbdDBb5fA==,type:str]
  - group: ENC[AES256_GCM,data:z0IvbUCgOLZ4+Q==,iv:eZe96Zzhv87ZAFC9wKHSPoyCA+xFvH4Hia/4kpAxUGM=,tag:NyMUcWnZkSAbfCyGiAy/hw==,type:str]
    repos:
      - ENC[AES256_GCM,data:QhZK3dNGQ/3hQ5ZBOC9Iu5b4SGT7R7b9HOn9PJmXEBiN,iv:i9N2fDhM3TGLPZ0dk48w5S31CeM4JPD3EYWw/iWNuJ0=,tag:efGsJCCfxAtB5VpzRco8+Q==,type:str]
      - ENC[AES256_GCM,data:/juX6fAyDgTQk+UojTy1,iv:TvvJ3z9RD/YW0jZ9VOpyNtaNbJE/tqPhXPj/kyb9KR0=,tag:zVQHcpxoqE82xy7VyJgF0A==,type:str]
      - ENC[AES256_GCM,data:6hOthamwJoh5SlGB9PjJk80G,iv:tLRzow8Bch9HzRarM6WqzD5HFbsaQ+Q+Sc3cBaAiuig=,tag:xTAto9JpH/fs5euJ71kTOg==,type:str]
      - ENC[AES256_GCM,data:1GXplVuNdhQlk1kgyRUDQg==,iv:rHQp9Qp10WtbRF7w30hwBaMfjpY3xlD8AufN42okvKI=,tag:YE8/kkD1Lv8kQGLkcil3Dw==,type:str]
      - ENC[AES256_GCM,data:5MKE0AvTo2w/3JnxlQ==,iv:sc1hyrprTipKQu2R0/sfsQu7Ec+ibvetEFhPzGzH9wM=,tag:64zmHXty75th+4VMVZIhoA==,type:str]
      - ENC[AES256_GCM,data:lRimwW3hK1mxE8MbSw==,iv:KYufsHd6DNbQdafvm9f+f+VP2FBhJDroq2yGx6Z8iFc=,tag:AOP/cdshRzda8Sa+K863bA==,type:str]
  - group: ENC[AES256_GCM,data:BL5+Ecn3rL4=,iv:8akR+MhjnzE148mLaxgoI4e3GGflX/Y73Fxc0G6gZAY=,tag:T8dxw0/K4KAN9pWY7Olyzg==,type:str]
    repos:
      - ENC[AES256_GCM,data:JkVNJMlOC+cLgj6vJGY=,iv:OTk8J1W5TdD1ogkXWXnYZUTP1vaSrZH4XmUrl7zRDJ4=,tag:gDQih7T3RbSVW9nOK2/kWg==,type:str]
      - ENC[AES256_GCM,data:LmcnR4D8vQ==,iv:c+qbznAsidSoIPlUXa5EKCBKiuy36G99Bs80BsUS7LA=,tag:lz85jQw6JaK8pjYhZLp0WQ==,type:str]
      - ENC[AES256_GCM,data:Sh7h2sAf3SqogkacLg==,iv:gsbfT6oQj450K0m4vAdbEWFKhZAjP7PO5RbL7HQ5ZSk=,tag:Ocf1IrpazXMfekX6rwQWGA==,type:str]
      - ENC[AES256_GCM,data:8lAxmJKU5CqjYucOgIvYagAYE0t6,iv:zN+jYOFsrPwNwWg6u/SZv4Kwa9JXm8mzOrdEfuwrD/M=,tag:OsGp8iR743+IwBYT/MbU5w==,type:str]
      - ENC[AES256_GCM,data:lF0fY9u+WZw/boXtwerWe8RmtA==,iv:zmh6MgYsJc6VST92XqC3y164SLw6McQOzaPJH9hKxVQ=,tag:PApkgkfSzPNenOoQXyZWAA==,type:str]
      - ENC[AES256_GCM,data:DPayTFtjYHzKet/yKQAh+8BmmlU1oKCZ0fQ=,iv:quB3iNzBhCmmvDDElpzT6AdeJlo9OdXexLeKuaSGkZY=,tag:m3FId3nR0xWD8CVeyrW5Xg==,type:str]
      - ENC[AES256_GCM,data:KcurY5ONQS7ro+/N9WOQnqyIZVAM3w==,iv:oVpLBurOGStZMd13sX59gId8bvZaJ7KSVlSEcl+hH3k=,tag:vcH5wL13G2K07ynBx5B8FA==,type:str]
      - ENC[AES256_GCM,data:W+Bs84sI24DLlU4YTjq/lu6+S5PABe+pgrLKCQWdxMXQ,iv:BY7ULmQhkFEfWd7LtPvFhId6/645TvMSxWCIfPZ0IVA=,tag:HrhXME7qAn2HT/bvLzGGdw==,type:str]
      - ENC[AES256_GCM,data:3RXgr/ywECj1c5G4,iv:y3+Df36aDzB2jRO8fw2mBLtEcMdpgPPSJ/zvke+1Ce0=,tag:jgD9YyCT0PzX+oXWBSbYqw==,type:str]
      - ENC[AES256_GCM,data:+6K8322/IrVJ+guG48i6gz8OVSL/rv0+rV+lDS3E,iv:mqYpHH0u6ObKPiJdriF0TzJMRi1yHCXAszPpnJzF0rc=,tag:mOyWVB5RciY1cl0A+dZ20g==,type:str]
      - ENC[AES256_GCM,data:dVKn/yFElrwg1huPKuO28nCrUtj9Mel7Mut/tT8=,iv:1KYqGTbmZ2RjPcJgNM2fjwkOQXHur4FlyYNkvbG162w=,tag:oRd+dK8REQNv5vdV2IdRdQ==,type:str]
  - group: ENC[AES256_GCM,data:lj+hJkc=,iv:XoTBLCe5HHISyqX2R4sDGZqF37NbuA22p0JRiZV53Ew=,tag:k6rImvXMLZrW/DEmGdvzaQ==,type:str]
    repos:
      - ENC[AES256_GCM,data:3r6TKnsmY85NHJmfA0Xf7E62,iv:W4WFGQzHqFQTlF/5ax006HMIwKSVRaWWQvd2zTP6Kj8=,tag:R2YSSZtOKrVumSYzCtwm0Q==,type:str]
      - ENC[AES256_GCM,data:LB7W5kVK8+Gjrj0=,iv:FSq+geJEmgS5fZT2JiOw1NH8dtkHGb3d0yUWBzaTjxs=,tag:WX4og/JZm16kvH6uzTowng==,type:str]
      - ENC[AES256_GCM,data:P+HSrsSoknU9nybO7Q==,iv:54WCST3BxtWc2J70BS5pBF4RudjJe8iZdQcN/7q5tkc=,tag:D2YhcgFxd7yvV1kannF7sQ==,type:str]
      - ENC[AES256_GCM,data:hATFzr7THlcI1Nk=,iv:TP8cV/PcdUpknuDsl7xkotPThBx4qLSMkViWsME9iRk=,tag:RdYf580iV272SuADvNfPXQ==,type:str]
      - ENC[AES256_GCM,data:9VBIk+3dP1RLUIH+l4RoDbKLHw==,iv:Ll3v7kvvlaWVZioNJe04zXvsf5eltxGZV9+5iEuaIn0=,tag:LKAPlx0dkz3OVzvxqi4kmw==,type:str]
      - ENC[AES256_GCM,data:xGDvIhDK,iv:d7RE5vA/bBvPpyiJCTj86IJPyqOOIQx1eR9STljIzlY=,tag:JVWiR94pVYFoyLaWz8jB/Q==,type:str]
      - ENC[AES256_GCM,data:AmWkrRYELaaoVIqH76sOU153lw==,iv:uQgfEk2xxuzyemitrr/PVi56fG/9kNWOSFewv2hl+zk=,tag:N7fymslsWDUAtYyf261Iug==,type:str]
      - ENC[AES256_GCM,data:Qqj0QlKRmAUatg==,iv:kDUU0sM7wU38h9TaUQUoFtpyZb32nYuPAZs1iPC9JYU=,tag:bPKxY6X0cEYuUUrkRDdVoA==,type:str]
      - ENC[AES256_GCM,data:QGIREXgZw2UI,iv:BzqJWgazzTbmwTQTWw+mXJzjjcstu49d6ZFQFRm1Arc=,tag:zLfNxn94DNItIrjNUyqxow==,type:str]
      - ENC[AES256_GCM,data:c1zOEQ==,iv:Ms+FKijcvDwZoDCqBLiiEahXKLo+xIGVigvVpxUGjDE=,tag:pEPcx0yKncuBcc0EIKH1IA==,type:str]
      - ENC[AES256_GCM,data:U3xHia0B3GMX+u7r5VE=,iv:ezTXhPNcnB1scnGCMzU2+w8CTTSm8TUlqSX8NAONhhM=,tag:IS99G2o2lAkgLJZxJwhb3Q==,type:str]
      - ENC[AES256_GCM,data:MsEN2buRRwcfa2NTFoT4hQ==,iv:gsaXrDLr25zVcxNrFCvlNYMqeb9e6Tdn2j5fabFTaRs=,tag:nfJu2cBEHNhipQ2qIcQwpw==,type:str]
      - ENC[AES256_GCM,data:Qe7fqQ==,iv:92sVm8T5B3aXsuki0MA7o2LuPcL2C/QU+bsDXODdLd8=,tag:AON7940m9IHTJPNVDkTGdQ==,type:str]
      - ENC[AES256_GCM,data:hAvO9TqdGUCefpyvFlOiTJ/H7Q==,iv:71fiJrKrn4mj59B3I6c1dCEe5VlletDKilAUriMuN+0=,tag:mnzZrapuJsiXITB1Eai9bQ==,type:str]
      - ENC[AES256_GCM,data:w7DNc/aq2qcOw1fFd8LeOQ==,iv:aDX+lqVf0GVxjWn8zAHIUPoH0w75UglRtmu8Xrx3FjI=,tag:io2J3jjgM+m1Lp93+G0Pag==,type:str]
excludeRepos:
  - ENC[AES256_GCM,data:01riKzO7dOLvt+RraoKN,iv:ZdsGJhjCAcsZOGx5jK5WQnpyeI5tyJy5SdwppjAvDng=,tag:r8OBu/Ikm70FIzccW3ZrLQ==,type:str]
  - ENC[AES256_GCM,data:2m8N0quo3w==,iv:9O6Z+5UbW909PwNfyqKy5Qoj3rHoeL5ELxZPlZ5AbJs=,tag:HP1SUPLZU4reFvKogxEl3w==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1hae0mml9ktpyjpmkcfahpzhk2xuckyn2gnw8tr3a6y6yz8gv9qyqr65n9h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJSXlRbGYyOGlSQUlvU2hN
        R3Q1dWQ5cnpFVmNiOWNLVWhpeEtNaGlLK2pnCjEvc2pheVZGanBmbUhUMm5keDNw
        Sk9ZRDRnTEtDL09jSFdOdG1FdklQTUkKLS0tIFREOWkwTWI1TklXTUROTmdYNDY0
        czIrbURXeTZLRnEwd2tDMFowbEpKRHcKKhzS51Uw71ChHs8Fif/N7MRoccrossPx
        hBU9oOtorTdL+puqWkDLMZr3jyZA/sLDDpsAbDXajSoDfGXFP7dmRw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-10-20T09:07:48Z"
  mac: ENC[AES256_GCM,data:12brSkwvKlyi1M5PV1uSs2/txdUtppWnUERWYoKseN+wcj3bsRKy3X2G66hipPHfHzVxk6jZZb9W561ewadFBCN5EGio0Uia+uMcq/QoOes6lhVWmzObN5Z8HRk0BY0PNsudfxxIKpexw3fBaKliQpuBEy+FAuJ4G64jwtfLjto=,iv:cNhT/LnRXGEoI1EYkxhIKzoJpbfHRq5qv0SOA3+znvA=,tag:mZ9KevsCyhEVkvlNVE+UDw==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.9.0
